# Auto-generated bird name mapping
bird_name_mapping = {
    "Background Noise": 0,
    "Black-headed Gull": 1,
    "Canada Goose": 2,
    "Carrion Crow": 3,
    "Common Chaffinch": 4,
    "Common Kingfisher": 5,
    "Common Redstart": 6,
    "Dunnock": 7,
    "Eurasian Blackbird": 8,
    "Eurasian Blackcap": 9,
    "Eurasian Blue Tit": 10,
    "Eurasian Bullfinch": 11,
    "Eurasian Coot": 12,
    "Eurasian Golden Oriole": 13,
    "Eurasian Jay": 14,
    "Eurasian Nuthatch": 15,
    "Eurasian Siskin": 16,
    "Eurasian Treecreeper": 17,
    "Eurasian Wren": 18,
    "European Goldfinch": 19,
    "European Robin": 20,
    "Goldcrest": 21,
    "Great Spotted Woodpecker": 22,
    "Great Tit": 23,
    "Hawfinch": 24,
    "Hooded Crow": 25,
    "Long-tailed Tit": 26,
    "Mallard": 27,
    "Marsh Tit": 28,
    "Redwing": 29,
    "Rook": 30,
    "Short-toed Treecreeper": 31,
    "Stock Dove": 32,
}
