selected_birds = [
    "Black-headed Gull",
    "Canada Goose",
    "Carrion Crow",
    "Common Blackbird",
    "Common Chaffinch",
    "Common Kingfisher",
    "Common Redstart",
    "Common Wood Pigeon",
    "Dunnock",
    "Eurasian Blackcap",
    "Eurasian Blue tit",
    "Eurasian Bullfinch",
    "Eurasian Coot",
    "Eurasian Golden Oriole",
    "Eurasian Jay",
    "Eurasian Nuthatch",
    "Eurasian Siskin",
    "Eurasian Treecreeper",
    "Eurasian Wren",
    "European Goldfinch",
    "European Robin",
    "Goldcrest",
    "Great Spotted Woodpecker",
    "Great Tit",
    "Hawfinch",
    "Hooded Crow",
    "Lesser Black-backed Gull",
    "Long-tailed Tit",
    "Mallard",
    "Marsh Tit",
    "Redwing",
    "Rook",
    "Short-toed Treecreeper",
    "Stock Dove",
    "Background Noise",
]

bird_name_mapping = {
    "Black-headed Gull": 0,
    "Canada Goose": 1,
    "Carrion Crow": 2,
    "Common Blackbird": 3,
    "Common Chaffinch": 4,
    "Common Kingfisher": 5,
    "Common Redstart": 6,
    "Common Wood Pigeon": 7, # 删除
    "Dunnock": 8,
    "Eurasian Blackcap": 9,
    "Eurasian Blue tit": 10,
    "Eurasian Bullfinch": 11,
    "Eurasian Coot": 12,
    "Eurasian Golden Oriole": 13,
    "Eurasian Jay": 14,
    "Eurasian Nuthatch": 15,
    "Eurasian Siskin": 16,
    "Eurasian Treecreeper": 17,
    "Eurasian Wren": 18,
    "European Goldfinch": 19,
    "European Robin": 20,
    "Goldcrest": 21,
    "Great Spotted Woodpecker": 22,
    "Great Tit": 23,
    "Hawfinch": 24,
    "Hooded Crow": 25,
    "Lesser Black-backed Gull": 26,
    "Long-tailed Tit": 27,
    "Mallard": 28,
    "Marsh Tit": 29,
    "Redwing": 30,
    "Rook": 31,
    "Short-toed Treecreeper": 32,
    "Stock Dove": 33,
}


birds = {
    "Aegithalos+caudatus": "Long-tailed Tit",
    "Poecile+palustris": "Marsh Tit",
    "Chroicocephalus+ridibundus": "Black-headed Gull",
    "Corvus+frugilegus": "Rook",
    "Turdus+iliacus": "Redwing",
    "Alcedo+atthis": "Common Kingfisher",
    "Prunella+modularis": "Dunnock",
    "Coccothraustes+coccothraustes": "Hawfinch",
    "Sitta+europaea": "Eurasian Nuthatch",
    "Columba+oenas": "Stock Dove",
    "Branta+canadensis": "Canada Goose",
    "Corvus+corone": "Carrion Crow",
    "Turdus+merula": "Common Blackbird",
    "Fringilla+coelebs": "Common Chaffinch",
    "Phoenicurus+phoenicurus+phoenicurus": "Common Redstart",
    "Sylvia+atricapilla": "Eurasian Blackcap",
    "Cyanistes+caeruleus": "Eurasian Blue tit",
    "Pyrrhula+pyrrhula": "Eurasian Bullfinch",
    "Fulica+atra": "Eurasian Coot",
    "Oriolus+oriolus": "Eurasian Golden Oriole",
    "Garrulus+glandarius": "Eurasian Jay",
    "Spinus+spinus": "Eurasian Siskin",
    "Certhia+familiaris": "Eurasian Treecreeper",
    "Troglodytes+troglodytes": "Eurasian Wren",
    "Carduelis+carduelis": "European Goldfinch",
    "Erithacus+rubecula": "European Robin",
    "Regulus+regulus": "Goldcrest",
    "Dendrocopos+major": "Great Spotted Woodpecker",
    "Parus+major": "Great Tit",
    "Corvus+cornix": "Hooded Crow",
    "Anas+platyrhynchos": "Mallard",
    "Certhia brachydactyla	": "Short-toed Treecreeper",
}


bird_name_mapping = {
    "Black-headed Gull": 0,
    "Canada Goose": 1,
    "Carrion Crow": 2,
    "Common Blackbird": 3,
    "Common Chaffinch": 4,
    "Common Kingfisher": 5,
    "Common Redstart": 6,
    "Common Wood Pigeon": 7,  # 删除
    "Dunnock": 8,
    "Eurasian Blackcap": 9,
    "Eurasian Blue tit": 10,
    "Eurasian Bullfinch": 11,
    "Eurasian Coot": 12,
    "Eurasian Golden Oriole": 13,
    "Eurasian Jay": 14,
    "Eurasian Nuthatch": 15,
    "Eurasian Siskin": 16,
    "Eurasian Treecreeper": 17,
    "Eurasian Wren": 18,
    "European Goldfinch": 19,
    "European Robin": 20,
    "Goldcrest": 21,
    "Great Spotted Woodpecker": 22,
    "Great Tit": 23,
    "Hawfinch": 24,
    "Hooded Crow": 25,
    "Long-tailed Tit": 26,
    "Mallard": 27,
    "Marsh Tit": 28,
    "Redwing": 29,
    "Rook": 30,
    "Short-toed Treecreeper": 31,
    "Stock Dove": 32,
    "Background Noise": 33
}